english:
  users:
    - CNN
    - bbcnews
    - VOAvideo
  playlists:
    -
hindi:
  users:
    - aajtaktv
  playlists:
    -
german:
  users:
    - deutschewelle
    - euronewsde
    - N24de
  playlists:
    -
french:
  users:
    - france24
  playlists:
    -
